language: node_js
node_js:
- 'lts/*'
sudo: false
deploy:
  provider: npm
  email: trustmaster@kodigy.com
  api_key:
    secure: Q6tuXWydqP1OSNuRUOaiBwasx3NiwN3WiNaIb9TvnoYom1iaCssG5s62I7q+NoeIjQoDUXcQ+FW/8bKgqdFb8Mi5Xp5S+W0gkWQGD+gWOcrIrjNAs8Ar3tZNhn4rDOOfwOTcpt9plVWHiUcEpxXCChvpdbSQc6EofKPvPERvNG7JcVOFYSN8S8Dkxp9wJyRHxXa0prht9Ypkh0+e1yHb2Xj3hpMHrS613hvKFokQ9RWI5sbQZz8APiXg5h3KWlRAOT01ki0IMszZHM1bk7m41RLGx2ftjNFUhN//ImARQ3Z2XMw8AIGQLKLyx+ETRLxRyXHTd2kt8Fw5G3vLs1+1ITi3a6m8A2IsvA1wK5kQWzkYL1bx1PK459lB4+kS6DM5e5ZhQW8hZmJsLI/SxdAt0g0b9s0+PDuIJ0qyeATj8KGU4M8hHk5nDQSqmwbl+pz1BdbVK4MmQf3/ZAGiiKVCUXOXv4+LB0sdKfen9Gyt9inkM3kfeX80ZxOzZqgpVG+B6bYTJVbdDyKgi4lTJekeiWjlb5PO3mvRubPMLyzVCIzrnfyX/7+1KDI5EzCyd5CdrHJcLZG6omg+LecnlB1qVnvaVD85jovU6XqUt8A1gNEI+qiI8CiXmrEnFifpRHAxG1N1+ONa+DzTkLzyk0/fqNw188WUXtQZjDaDSQtbrJk=
  on:
    tags: true
    repo: noflo/noflo-assembly
